---

- block:
    - name: Ensure needed python packages are isntalled
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
      with_items:
        - "{{ artcl_sphinx_pip_requirements }}"

    - name: Create empty directory to write templates to
      file:
        path: "{{ artcl_docs_source_dir }}/{{ artcl_docs_templates_dirname }}"
        force: yes
        state: directory

    - name: Copy rst documents to sphinx source dir
      shell: >
        cp "{{ artcl_collect_dir }}/undercloud/home/stack/{{ item }}.gz" "{{ artcl_docs_source_dir }}/{{ artcl_docs_templates_dirname }}"
      with_items: "{{ artcl_doc_whitelist }}"
      ignore_errors: yes

    - name: Unarchive rst documents
      shell: >
        gunzip "{{ artcl_docs_source_dir }}/{{ artcl_docs_templates_dirname }}/{{ item }}.gz";
      with_items: "{{ artcl_doc_whitelist }}"
      ignore_errors: yes

    - name: Generate fresh index.rst for Sphinx
      template:
        src: index.rst.j2
        dest: "{{ artcl_docs_source_dir }}/index.rst"
        force: yes

    - name: Build docs via tox
      shell: >
        cd "{{ artcl_docs_source_dir }}"/..;
        sphinx-build -b html "{{ artcl_docs_source_dir }}" "{{ artcl_docs_build_dir }}"
      register: result

    - debug: var=result.stdout_lines

  delegate_to: localhost
  run_once: true
  when: artcl_gen_docs|bool
