---

- block:
    #internal-ci
    - name: upload to the artifact server using pubkey auth
      shell: >
        rsync -av -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" {{ artcl_collect_dir }}/ {{ artcl_rsync_path }}/$BUILD_TAG
      retries: 5
      delay: 60
      when: artcl_rsync_use_daemon == false

    #centos-ci
    - name: upload to the artifact server using password auth
      environment:
        RSYNC_PASSWORD: "{{ lookup('env', 'RSYNC_PASSWORD') }}"
      shell: >
        rsync -av {{ artcl_collect_dir }}/ {{ artcl_rsync_path }}/$BUILD_TAG
      retries: 5
      delay: 60
      when: artcl_rsync_use_daemon == true

    - name: create the artifact location redirect file
      template:
        src: full_logs.html.j2
        dest: "{{ artcl_collect_dir }}/full_logs.html"
  delegate_to: localhost
