---

- block:
    - name: upload to the artifact server using rsync
      command: rsync -av -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" {{ artcl_collect_dir }}/ {{ artcl_rsync_path }}/{{ lookup('env', 'BUILD_TAG' }}
      environment:
        RSYNC_PASSWORD: "{{ lookup('env', 'RSYNC_PASSWORD') }}"
      changed_when: true
      retries: 5
      delay: 60
      when: artcl_use_rsync|bool

    - name: upload to swift based artifact server
      command: swift upload --header "X-Delete-After:{{ artcl_swift_delete_after }}" logs/{{ lookup('env', 'BUILD_TAG') }} *
      args:
        chdir: "{{ artcl_collect_dir }}"
      changed_when: true
      environment:
        OS_AUTH_URL: {{ artcl_swift_auth_url }}
        OS_USERNAME: {{ artcl_swift_username }}
        OS_PASSWORD: {{ artcl_swift_password }}
        OS_TENANT_NAME: {{ artcl_swift_tenant_name }}
      when: artcl_use_swift|bool

    - name: create the artifact location redirect file
      template:
        src: full_logs.html.j2
        dest: "{{ artcl_collect_dir }}/full_logs.html"
  delegate_to: localhost
