artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - undercloud-post-install
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - add-provisioning-interface
    - validate-overcloud-ipmi-connection
    - add-disk-size-hint
    - adjust-interface-mtus
  included_oooq_docs:
    - baremetal-overcloud/introduction
    - baremetal-overcloud/requirements-networking
    - baremetal-overcloud/virtual-vs-baremetal-undercloud
    - baremetal-overcloud/env-setup
    - baremetal-overcloud/customizing-undercloud-conf
    - baremetal-overcloud/copying-customized-files
    - baremetal-overcloud/env-specific-pre-deploy-steps
    - baremetal-overcloud/customizing-external-network-vlan
    - baremetal-overcloud/validate-prior-to-deploy
  table_of_contents:
    - introduction
    - requirements-networking
    - virtual-vs-baremetal-undercloud
    - env-setup
    - add-provisioning-interface
    - validate-overcloud-ipmi-connection
    - customizing-undercloud-conf
    - undercloud-install
    - copying-customized-files
    - env-specific-pre-deploy-steps
    - add-disk-size-hint
    - adjust-interface-mtus
    - undercloud-post-install
    - customizing-external-network-vlan
    - validate-prior-to-deploy
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate


