artcl_gzip_only: true
artcl_artifact_url: https://ci.centos.org/artifacts/rdo
artcl_publish: true
artcl_use_rsync: true
artcl_rsync_use_daemon: true
artcl_rsync_path: rdo@artifacts.ci.centos.org::rdo
